# Generated by Django 4.1.12 on 2023-11-03 11:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("account", "0002_images_images_account_ima_created_713f72_idx"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Images",
            new_name="Image",
        ),
        migrations.RenameIndex(
            model_name="image",
            new_name="account_ima_created_ea74f6_idx",
            old_name="account_ima_created_713f72_idx",
        ),
    ]
